### PR TITLE
Lms 1 mblr for homepage

### PR DESCRIPTION
**Pull request by OlegAngelo**

### CODE REVIEW

**Review by JadeParan — APPROVED** [review]
good

**Comment by JadeParan** [comment]
good

**Review by JadeParan — APPROVED** [review]

**Review by JadeParan — APPROVED** [review]
i approve

**Review by JadeParan — APPROVED** [review]
good for merging

**Review by RonnelDave — APPROVED** [review]

**Review by JadeParan — APPROVED** [review]
approved

**Comment by JadeParan** [comment]
hey

**Pull request merged**
